# ---- DRY anchors -----
x-common-env: &common_env
  PUID: ${PUID:-1000}
  PGID: ${PGID:-1000}
  TZ: ${TZ:-America/New_York}
  UMASK: ${UMASK:-002}

x-common-service: &common_service
  restart: unless-stopped
  networks:
    - media-net

# Base path can be overridden via .env: BASE=/some/other/path
# Defaults to /home/user/jfh
networks:
  media-net: {}

services:
  qbittorrent:
    <<: *common_service
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbt
    environment:
      - WEBUI_PORT: 8080
    volumes:
      - ${BASE:-/home/atsinna/jfh}/configs/qbt:/config
      - ${BASE:-/home/atsinna/jfh}/downloads:/downloads
    ports:
      - "8080:8080"       # Web UI
      - "6881:6881"       # BitTorrent TCP
      - "6881:6881/udp"   # BitTorrent UDP

  prowlarr:
    <<: *common_service
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment: *common_env
    volumes:
      - ${BASE:-/home/atsinna/jfh}/configs/prowlarr:/config
    ports:
      - "9696:9696"

  sonarr:
    <<: *common_service
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment: *common_env
    volumes:
      - ${BASE:-/home/atsinna/jfh}/configs/sonarr:/config
      - ${BASE:-/home/atsinna/jfh}/downloads:/downloads
      - ${BASE:-/home/atsinna/jfh}/media:/media
    ports:
      - "8989:8989"

  radarr:
    <<: *common_service
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment: *common_env
    volumes:
      - ${BASE:-/home/atsinna/jfh}/configs/radarr:/config
      - ${BASE:-/home/atsinna/jfh}/downloads:/downloads
      - ${BASE:-/home/atsinna/jfh}/media:/media
    ports:
      - "7878:7878"

  jellyfin:
    <<: *common_service
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment: *common_env
    volumes:
      - ${BASE:-/home/atsinna/jfh}/configs/jellyfin:/config
      - ${BASE:-/home/atsinna/jfh}/configs/jellyfin/cache:/cache
      - ${BASE:-/home/atsinna/jfh}/media:/media
    ports:
      - "8096:8096"       # HTTP - Troublshoot porting w/ http://localhost:8096/web
